### ISSUE TITLE
Пермишены

### ISSUE THREAD

**Issue by MrVSV** [maiow/dog-shelter#21]
Мы же звоним и все такое

**Comment by maiow** [comment]
У нас интент всего лишь и наша прилка сама сейчас не использует ничего, на что пермишен нужен) кроме интернета, на который пермишен есть) Из всего списка пермишенов[https://developer.android.com/reference/android/Manifest.permission] подумать стоит над access_network_state/access_wifi_state. Может быть позже READ_CONTACTS (пока не нужен вообще).
