### ISSUE TITLE
Фильтры сбрасываются при переходе на другую вкладку

### ISSUE THREAD

**Issue by SR-rodi** [maiow/dog-shelter#48]
фильтры сбрасываются при переходе на другую вкладку, когда делаешь поиск, и потом возвращаешься назад, то параметры поиска сбрасываются - не удобно - 3 таких комментария.

**Comment by Gittestempty** [comment]
Сделано в 1.0.0

**Comment by maiow** [comment]
исправлено в версии 1.0.0
