### ISSUE TITLE
Firebase и Юнит тесты. Инфа для подумать

### ISSUE THREAD

**Issue by MrVSV** [maiow/dog-shelter#6]
Сейчас смотрел вводную конфу у кипаро

Говорят, что в большинстве случаев фб - плохое решение

Также рассказали, что во многих компаниях, если процент кода, покрытого юнит тестами меньше какого-то порога, то даже на программном уровне не даёт сделать пулреквест

**Comment by maiow** [comment]
Firebase как вынужденное решение в отсутствии бэка. Когда заработает бэк с данными по собакам, можно будет обсуждать и перенос остального, а сейчас альтернативы нет пока.
