### ISSUE TITLE
Лупа в строке поиска

### ISSUE THREAD

**Issue by SR-rodi** [maiow/dog-shelter#67]
лупа в строке поиска кликабельной напрашивается – m3 guidelines: Icons and icon buttons, Leading icon: The left side of the bar should contain either a navigational action (such as a menu or up-arrow) or a non-functional search icon. – стоит забить на это, т.к. не по гайдлайнам

**Comment by maiow** [comment]
делать лупу кликабельной не будем - не по гугловским гайдлайнам
